### ISSUE TITLE
Need MinQueue/MaxQueue and maybe MinStack/MaxStack

### ISSUE THREAD

**Issue by cameroncuster** [lrvideckis/Programming-Team-Code#62]

**Comment by cameroncuster** [comment]
Reference code https://github.com/ucf-programming-team/hackpack-cpp/blob/lightseba-general-changes/content/data-structures/MonotonicQueue.h [hackpack-cpp]

**Comment by lrvideckis** [comment]
Why not just use that code?

**Comment by cameroncuster** [comment]
It's fair, add to README then?
